# Generated by Django 4.2 on 2023-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('factory_year', models.IntegerField(blank=True, null=True)),
                ('brand_year', models.IntegerField(blank=True, null=True)),
                ('plate', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/medias')),
            ],
        ),
    ]
